In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [26]:
df = pd.read_csv('cleaned_food_delivery.csv')

In [27]:
def age_group(age):
    if age < 25:
        return 'Young Adult'
    elif age < 40:
        return 'Adult'
    elif age < 55:
        return 'Middle Age'
    else:
        return 'Senior'

df['Age_Group'] = df['Customer_Age'].apply(age_group)

In [28]:
def delivery_category(time):
    if time <= 60:
        return 'Fast'
    elif time <= 180:
        return 'Average'
    else:
        return 'Slow'

df['Delivery_Category'] = (
    df['Delivery_Time_Min']
    .apply(delivery_category)
)

In [29]:
def revenue_category(value):
    if value < 1000:
        return 'Low'
    elif value < 3000:
        return 'Medium'
    else:
        return 'High'

df['Revenue_Category'] = (
    df['Final_Amount']
    .apply(revenue_category)
)

In [30]:
def profit_category(margin):
    if margin < 0:
        return 'Loss'
    elif margin < 0.2:
        return 'Low Profit'
    else:
        return 'High Profit'

df['Profit_Category'] = (
    df['Profit_Margin']
    .apply(profit_category)
)

In [31]:
df[['Age_Group',
    'Delivery_Category',
    'Revenue_Category',
    'Profit_Category']].head()

     Age_Group Delivery_Category Revenue_Category Profit_Category
0  Young Adult              Slow           Medium      Low Profit
1        Adult              Fast             High     High Profit
2        Adult              Slow              Low      Low Profit
3        Adult           Average           Medium      Low Profit
4       Senior              Fast              Low      Low Profit

In [32]:
df.to_csv(
    'final_food_delivery.csv',
    index=False
)

In [33]:
df.head()

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,Order_Time,Delivery_Time_Min,Distance_km,Order_Value,Discount_Applied,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin,Delivery_Rating_Filled,Age_Group,Delivery_Category,Revenue_Category,Profit_Category
0,ORD000001,CUST6948,19.0,Male,Hyderabad,Central,RES936,Restaurant_29,Chinese,2024-10-20,0:00,187.0,15.75,1197.0,50.0,1147.0,UPI,Delivered,NaN,DP563,5.0,4.4,Weekend,True,0.13,5.0,Young Adult,Slow,Medium,Low Profit
1,ORD000002,CUST6515,39.0,Female,Chennai,North,RES689,Restaurant_419,Chinese,2024-08-12,0:00,20.0,29.50,4869.0,20.0,4849.0,COD,Delivered,NaN,DP369,5.0,4.7,Weekday,True,0.48,5.0,Adult,Fast,High,High Profit
2,ORD000003,CUST1765,39.0,Male,Delhi,South,RES723,Restaurant_244,Arabian,2024-12-08,0:00,207.0,9.97,757.0,20.0,737.0,Wallet,Delivered,NaN,DP580,4.0,4.9,Weekend,True,0.08,4.0,Adult,Slow,Low,Low Profit
3,ORD000004,CUST2744,39.0,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,2024-10-08,0:00,143.0,15.68,1197.0,50.0,1147.0,UPI,Cancelled,Late Delivery,DP155,2.0,3.4,Weekday,False,0.04,2.0,Adult,Average,Medium,Low Profit
4,ORD000005,CUST4389,57.0,Female,Chennai,South,RES419,Restaurant_262,Chinese,2024-02-04,0:00,51.0,9.60,372.0,20.0,352.0,Card,Delivered,NaN,DP728,2.0,4.4,Weekend,False,0.12,2.0,Senior,Fast,Low,Low Profit

In [34]:
df.isnull().sum().sort_values(ascending=False)

Cancellation_Reason       90969
Delivery_Rating           16523
Order_Time                 1998
Order_Date                 1014
Customer_Age                  0
Customer_Gender               0
Area                          0
City                          0
Restaurant_Name               0
Restaurant_ID                 0
Cuisine_Type                  0
Delivery_Time_Min             0
Order_ID                      0
Customer_ID                   0
Order_Value                   0
Distance_km                   0
Discount_Applied              0
Final_Amount                  0
Order_Status                  0
Payment_Mode                  0
Delivery_Partner_ID           0
Restaurant_Rating             0
Order_Day                     0
Peak_Hour                     0
Profit_Margin                 0
Delivery_Rating_Filled        0
Age_Group                     0
Delivery_Category             0
Revenue_Category              0
Profit_Category               0
dtype: int64

In [36]:
df.shape

(100000, 30)

In [37]:
df.to_csv(
    'final_food_delivery.csv',
    index=False
)